// Generated by CoffeeScript 1.9.3
(function() {
  var BrowserWindow, Main, app, reporter,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  app = require('app');

  BrowserWindow = require('browser-window');

  reporter = require('crash-reporter');

  Main = (function() {
    function Main() {
      this.onQuit = bind(this.onQuit, this);
      this.onWindowAllClosed = bind(this.onWindowAllClosed, this);
      this.onReady = bind(this.onReady, this);
      reporter.start();
      app.on('ready', this.onReady);
      app.on('window-all-closed', this.onWindowAllClosed);
      app.on('quit', this.onQuit);
    }

    Main.prototype.onReady = function(e) {
      var win;
      console.log('onReady');
      win = new BrowserWindow({
        width: 800,
        height: 600
      });
      return win.loadUrl('file://' + __dirname + '/index.html');
    };

    Main.prototype.onWindowAllClosed = function(e) {
      console.log('onWindowAllClosed');
      if (process.platform !== 'darwin') {
        return app.quit();
      }
    };

    Main.prototype.onQuit = function(e) {
      return log.Println('onQuit');
    };

    return Main;

  })();

  new Main;

}).call(this);
