// Generated by CoffeeScript 1.9.3
(function() {
  var $, Markdown, createClass, createMdElement, md2react, ref, render;

  window.React = (ref = require('react'), createClass = ref.createClass, $ = ref.createElement, render = ref.render, ref);

  md2react = require('md2react');

  createMdElement = function(md) {
    return md2react(md, {
      gfm: true,
      breaks: true,
      tables: true
    });
  };

  Markdown = createClass({
    render: function() {
      return $('div', {
        className: 'markdown-body'
      }, [this.state.content]);
    },
    getInitialState: function() {
      return {
        content: null
      };
    },
    update: function(md) {
      return this.setState({
        content: createMdElement(md)
      });
    }
  });

  module.exports = render($(Markdown, {}), document.body);

}).call(this);
